// Static route links
export const Links = {
  homePage: () => "/",
  signIn: () => "/sign-in",
  signUpPage: () => "/sign-up",
  findAJobPage: () => "/find-a-job",
  findATalentPage: () => "/find-a-talent",
  browseJobsPage: () => "/browse-jobs",
  browseTalentsPage: () => "/browse-talents",
  jobsBrowse: () => "/jobs",
  dashboardOverviewPage: () => "/dashboard",
  myJobsPosted: () => "/my-jobs",
  myBids: () => "/my-bids",
  jobCreatePage: () => "/jobs/create",
  userProfile: (userId: string) => `/profile/${userId}`,
  settingsPage: () => "/settings",
  paymentSettingsPage: () => "/payment-settings",
  userPackages: () => "/packages",
  choosePackagesPage: () => "/packages/choose",
  inboxPage: () => "/inbox",
  aboutUsPage: () => "/about",
  faqPage: () => "/faq",
  contactUsPage: () => "/contact",
  privacyPolicyPage: () => "/privacy-policy",
  profileSettingPage: () => "/profile/settings",
  adminDashboard: () => "/admin/dashboard",
}
